package org.wxc.opensources;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTRIBUTOR.
 */
public class Contributor {

    private Long id;
    /** Not-null value. */
    private String login;
    private int contributions;

    public Contributor() {
    }

    public Contributor(Long id) {
        this.id = id;
    }

    public Contributor(Long id, String login, int contributions) {
        this.id = id;
        this.login = login;
        this.contributions = contributions;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLogin() {
        return login;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogin(String login) {
        this.login = login;
    }

    public int getContributions() {
        return contributions;
    }

    public void setContributions(int contributions) {
        this.contributions = contributions;
    }

}
