package org.wxc.opensources;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.wxc.opensources.Contributor;

import org.wxc.opensources.ContributorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contributorDaoConfig;

    private final ContributorDao contributorDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contributorDaoConfig = daoConfigMap.get(ContributorDao.class).clone();
        contributorDaoConfig.initIdentityScope(type);

        contributorDao = new ContributorDao(contributorDaoConfig, this);

        registerDao(Contributor.class, contributorDao);
    }
    
    public void clear() {
        contributorDaoConfig.getIdentityScope().clear();
    }

    public ContributorDao getContributorDao() {
        return contributorDao;
    }

}
