package org.wxc.opensources;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String login;
    private int userId;
    /** Not-null value. */
    private String avatarUrl;
    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private String htmlUrl;
    /** Not-null value. */
    private String followersUrl;
    /** Not-null value. */
    private String followingUrl;
    /** Not-null value. */
    private String gistsUrl;
    /** Not-null value. */
    private String starredUrl;
    /** Not-null value. */
    private String subscriptionsUrl;
    /** Not-null value. */
    private String organizationsUrl;
    /** Not-null value. */
    private String reposUrl;
    /** Not-null value. */
    private String eventsUrl;
    /** Not-null value. */
    private String receivedEventsUrl;
    /** Not-null value. */
    private String type;
    private boolean site_admin;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String login, int userId, String avatarUrl, String url, String htmlUrl, String followersUrl, String followingUrl, String gistsUrl, String starredUrl, String subscriptionsUrl, String organizationsUrl, String reposUrl, String eventsUrl, String receivedEventsUrl, String type, boolean site_admin) {
        this.id = id;
        this.login = login;
        this.userId = userId;
        this.avatarUrl = avatarUrl;
        this.url = url;
        this.htmlUrl = htmlUrl;
        this.followersUrl = followersUrl;
        this.followingUrl = followingUrl;
        this.gistsUrl = gistsUrl;
        this.starredUrl = starredUrl;
        this.subscriptionsUrl = subscriptionsUrl;
        this.organizationsUrl = organizationsUrl;
        this.reposUrl = reposUrl;
        this.eventsUrl = eventsUrl;
        this.receivedEventsUrl = receivedEventsUrl;
        this.type = type;
        this.site_admin = site_admin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLogin() {
        return login;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogin(String login) {
        this.login = login;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** Not-null value. */
    public String getHtmlUrl() {
        return htmlUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHtmlUrl(String htmlUrl) {
        this.htmlUrl = htmlUrl;
    }

    /** Not-null value. */
    public String getFollowersUrl() {
        return followersUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowersUrl(String followersUrl) {
        this.followersUrl = followersUrl;
    }

    /** Not-null value. */
    public String getFollowingUrl() {
        return followingUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFollowingUrl(String followingUrl) {
        this.followingUrl = followingUrl;
    }

    /** Not-null value. */
    public String getGistsUrl() {
        return gistsUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGistsUrl(String gistsUrl) {
        this.gistsUrl = gistsUrl;
    }

    /** Not-null value. */
    public String getStarredUrl() {
        return starredUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStarredUrl(String starredUrl) {
        this.starredUrl = starredUrl;
    }

    /** Not-null value. */
    public String getSubscriptionsUrl() {
        return subscriptionsUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSubscriptionsUrl(String subscriptionsUrl) {
        this.subscriptionsUrl = subscriptionsUrl;
    }

    /** Not-null value. */
    public String getOrganizationsUrl() {
        return organizationsUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrganizationsUrl(String organizationsUrl) {
        this.organizationsUrl = organizationsUrl;
    }

    /** Not-null value. */
    public String getReposUrl() {
        return reposUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReposUrl(String reposUrl) {
        this.reposUrl = reposUrl;
    }

    /** Not-null value. */
    public String getEventsUrl() {
        return eventsUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEventsUrl(String eventsUrl) {
        this.eventsUrl = eventsUrl;
    }

    /** Not-null value. */
    public String getReceivedEventsUrl() {
        return receivedEventsUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReceivedEventsUrl(String receivedEventsUrl) {
        this.receivedEventsUrl = receivedEventsUrl;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public boolean getSite_admin() {
        return site_admin;
    }

    public void setSite_admin(boolean site_admin) {
        this.site_admin = site_admin;
    }

}
